platform :ios, '12.0'

target 'BikeRaceEscapeAxmol' do
  pod 'Google-Mobile-Ads-SDK', '~> 13.4.0'
  # Interstitial-only (we keep AdMob banners).
  # If you want to pin a specific version, add: , '~> <version>'
  pod 'ChartboostSDK'
end
