#include "PZLegacyCompat.h"
#include "AppDelegate.h"
#include "PZGGameFieldScene.h"
#include "PZGCharacterMenu.h"
#include "PZGLoadingScene.h"
#include "PZGMainMenuScene.h"
#include "SharedData/PZGSharedData.h"
#include "PZCrashReporter.h"
#include "Ads/AdsController.h"
#include "Ads/AdsConfig.h"
#include "Ads/Providers/AdsProviderAdMob.h"
#include "Ads/Providers/AdsProviderChartboost.h"
#include "Ads/Providers/AdsProviderMux.h"

#if (CC_TARGET_PLATFORM == CC_TARGET_PLATFORM_IOS)
    #include <Foundation/Foundation.h>
    #if __has_include(<GoogleMobileAds/GoogleMobileAds.h>)
        #import <GoogleMobileAds/GoogleMobileAds.h>
    #endif
#endif

USING_NS_AX;

AppDelegate::AppDelegate() = default;
AppDelegate::~AppDelegate() = default;

void AppDelegate::initGfxContextAttrs() {
    // red, green, blue, alpha, depth, stencil, multisamplesCount
    GfxContextAttrs gfxContextAttrs = {8, 8, 8, 8, 24, 8, 0};
    RenderView::setGfxContextAttrs(gfxContextAttrs);
}

void AppDelegate::setDebugModeEnabled(bool enable) {
    auto* gf = PZGGameFieldScene::shared();
    if (gf) gf->setDebugModeEnabled(enable);
}

bool AppDelegate::applicationDidFinishLaunching() {

    ax::setLogLevel(ax::LogLevel::Debug);

#if (CC_TARGET_PLATFORM == CC_TARGET_PLATFORM_IOS)
    NSLog(@"\n\n========== APP LAUNCH TEST (NSLog) ==========");
#endif

    AXLOGD("AXMOL DEBUG LOG TEST");
    fprintf(stderr, "\n========== AXMOL DEBUG LOG TEST (fprintf) ==========\n");
    fflush(stderr);

    AXLOGI("AXMOL INFO LOG TEST");
    fprintf(stderr, "========== AXMOL INFO LOG TEST (fprintf) ==========\n");
    fflush(stderr);

    AXLOGW("AXMOL WARNING LOG TEST");
    fprintf(stderr, "========== AXMOL WARNING LOG TEST (fprintf) ==========\n");
    fflush(stderr);

    AXLOGE("AXMOL ERROR LOG TEST");
    fprintf(stderr, "========== AXMOL ERROR LOG TEST (fprintf) ==========\n");
    fflush(stderr);

    AXLOGI("===== APPLICATION DID FINISH LAUNCHING =====");
    fprintf(stderr, "\n===== APPLICATION DID FINISH LAUNCHING ===== (fprintf)\n");
#if (CC_TARGET_PLATFORM == CC_TARGET_PLATFORM_IOS)
    NSLog(@"===== APPLICATION DID FINISH LAUNCHING ===== (NSLog)\n");
#endif
    fflush(stderr);

    AXLOGI("AppDelegate::applicationDidFinishLaunching begin");
    PZCrashReporter::install();
    AXLOGI("Crash report path: {}", PZCrashReporter::getCrashReportPath());
    auto* director = Director::getInstance();
    auto* renderView = director->getRenderView();
    if (!renderView) {
        renderView = RenderViewImpl::create("Bike Race Escape");
        director->setRenderView(renderView);
    }

    director->setAnimationInterval(1.0f / 60.0f);
    // Responsive resolution policy:
    // - `EXACT_FIT` stretches (non-uniform) -> bad for pixel art/UI
    // - `SHOW_ALL` letterboxes
    // - `NO_BORDER` crops
    // - `FIXED_HEIGHT` keeps vertical size stable and expands/shrinks horizontal view based on device AR.
    //   This avoids stretch while also avoiding letterbox/crop in most landscape iOS cases.
    renderView->setDesignResolutionSize(960, 640, ResolutionPolicy::FIXED_HEIGHT);

    auto* fileUtils = FileUtils::getInstance();
    std::vector<std::string> searchPaths = {
        "runtime/axslc",  // compiled shaders (generated by Axmol build)
        "runtime",
        // On Apple we package Content/* into the app bundle root (Images/..., Sounds/...) via ax_mark_multi_resources(RES_TO "Resources").
        // Keep both layouts in search paths to avoid platform-specific resource bugs.
        "Images/HD",
        "Images/SD",
        "Sounds",
        "Fonts",
        "Content/Images/HD",
        "Content/Images/SD",
        "Content/Sounds",
        "Content/Fonts",
        "Content",
        "",
    };
    fileUtils->setSearchPaths(searchPaths);

    // Log search paths for debugging resource loading issues
    auto allSearchPaths = fileUtils->getSearchPaths();
    AXLOGI("Resource search paths:");
    for (const auto& path : allSearchPaths) {
        AXLOGI("  - {}", path);
    }

    // Log font path for debugging - fonts are loaded on-demand by Label::createWithBMFont
    auto fontFullPath = fileUtils->fullPathForFilename("MainFont.fnt");
    if (!fontFullPath.empty()) {
        AXLOGI("MainFont.fnt found at: {}", fontFullPath);
    } else {
        AXLOGW("MainFont.fnt not found in search paths - labels may not render");
    }

    // Keep the old loading flow as the initial runtime entry.
    auto* scene = PZGLoadingScene::scene();
    if (!scene) {
        AXLOGE("PZGLoadingScene::scene() returned null");
        return false;
    }
    director->runWithScene(scene);
    AXLOGI("AppDelegate::applicationDidFinishLaunching end");
    return true;
}

void AppDelegate::scheduledLoading() {
    AXLOGI("AppDelegate::scheduledLoading begin");
    auto* director = Director::getInstance();
    // Legacy port: the old loading scene re-entered itself; that just creates a loop + black screen if any resource is missing.
    // Do the minimum bootstrap then go to the first real UI.
    auto* sd = PZGSharedData::sharedInstanse();
    if (sd) sd->readDataFromFile();

    // ---- Ads bootstrap (Content/ads.plist) ----
    {
        fprintf(stderr, "\n[ADS-BOOTSTRAP-START] Initializing ads system\n");
        fflush(stderr);
        AXLOGI("[ADS-INIT] Starting ads initialization");

        auto* ads = PZ::AdsController::shared();
        fprintf(stderr, "[ADS-BOOTSTRAP] AdsController::shared() = %p\n", ads);

        if (!ads) {
            AXLOGE("[ADS-INIT] CRITICAL: AdsController::shared() returned null!");
            fprintf(stderr, "[ADS-BOOTSTRAP-ERROR] AdsController is null!\n");
            fflush(stderr);
        } else {
            AXLOGI("[ADS-INIT] AdsController obtained successfully");
            fprintf(stderr, "[ADS-BOOTSTRAP] Calling loadConfigFromPlist()\n");

            ads->loadConfigFromPlist();
            AXLOGI("[ADS-INIT] Config loaded from plist");
            fprintf(stderr, "[ADS-BOOTSTRAP] Config loaded\n");

            // Respect "Remove Ads" purchase flag.
            if (auto* sc = PZSettingsController::shared()) {
                bool removeAds = sc->removeAds;
                ads->setAdsEnabled(!removeAds);
                AXLOGI("[ADS-INIT] Remove ads setting: {}, ads enabled: {}", removeAds, !removeAds);
                fprintf(stderr, "[ADS-BOOTSTRAP] Remove ads: %s\n", removeAds ? "YES" : "NO");
            }

            // Provider selection (AdMob banner + optional Chartboost interstitial).
            const auto& cfg = ads->config();
            AXLOGI("[ADS-INIT] Config admobEnabled: {}", cfg.admobEnabled);
            fprintf(stderr, "[ADS-BOOTSTRAP] AdMob enabled in config: %s\n", cfg.admobEnabled ? "YES" : "NO");

            if (cfg.admobEnabled || cfg.chartboost.enabled) {
                if (cfg.admobEnabled && cfg.chartboost.enabled) {
                    fprintf(stderr, "[ADS-BOOTSTRAP] Creating AdsProviderMux (AdMob banner + Chartboost interstitial)\n");
                    auto mux = std::make_unique<PZ::AdsProviderMux>(
                        std::make_unique<PZ::AdsProviderAdMob>(),
                        std::make_unique<PZ::AdsProviderChartboost>());

                    mux->setBannerInitKey(cfg.admob.appIdIOS);
                    mux->setInterstitialInitKey(cfg.chartboost.appIdIOS + std::string("|") + cfg.chartboost.appSignatureIOS);
                    ads->setProvider(std::move(mux));
                    AXLOGI("[ADS-INIT] AdsProviderMux set");
                } else if (cfg.chartboost.enabled) {
                    fprintf(stderr, "[ADS-BOOTSTRAP] Creating AdsProviderChartboost instance\n");
                    ads->setProvider(std::make_unique<PZ::AdsProviderChartboost>());
                    AXLOGI("[ADS-INIT] AdsProviderChartboost set");
                } else {
                    fprintf(stderr, "[ADS-BOOTSTRAP] Creating AdsProviderAdMob instance\n");
                    ads->setProvider(std::make_unique<PZ::AdsProviderAdMob>());
                    AXLOGI("[ADS-INIT] AdsProviderAdMob set");
                }

#if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
                fprintf(stderr, "[ADS-BOOTSTRAP] Calling ads->initialize() (provider-specific keys)\n");
                if (cfg.admobEnabled && cfg.chartboost.enabled) {
                    ads->initialize(""); // mux initializes sub-providers using per-provider init keys.
                } else if (cfg.chartboost.enabled) {
                    ads->initialize(cfg.chartboost.appIdIOS + std::string("|") + cfg.chartboost.appSignatureIOS);
                } else {
                    ads->initialize(cfg.admob.appIdIOS);
                }
                AXLOGI("[ADS-INIT] Initialized provider");

                // Test device ID setup is done in AdsProviderAdMobApple.mm
#elif (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
                ads->initialize(cfg.admob.appIdAndroid);
                AXLOGI("[ADS-INIT] Initialized with Android app ID: {}", cfg.admob.appIdAndroid);
#else
                ads->initialize("");
                AXLOGI("[ADS-INIT] Initialized with empty app ID (non-mobile platform)");
#endif
                fprintf(stderr, "[ADS-BOOTSTRAP-SUCCESS] Ads initialized successfully!\n");
                fflush(stderr);
            } else {
                AXLOGW("[ADS-INIT] No ads providers enabled in config - ads will not show");
                fprintf(stderr, "[ADS-BOOTSTRAP] Ads disabled - skipping provider setup\n");
            }
        }
    }

    // Start at legacy main menu (it knows how to bootstrap its own UI via load()).
    if (auto* scene = PZGMainMenuScene::scene()) {
        AXLOGI("PZGMainMenuScene created, children count: {}", scene->getChildren().size());

        // Try to find and load the main menu layer
        bool menuLoaded = false;
        if (!scene->getChildren().empty()) {
            for (auto child : scene->getChildren()) {
                if (auto* layer = dynamic_cast<PZGMainMenuScene*>(child)) {
                    AXLOGI("Found PZGMainMenuScene layer, calling load()");
                    layer->load("InterfaceMM");
                    menuLoaded = true;
                    break;
                }
            }
        }

        if (!menuLoaded) {
            AXLOGW("Warning: Could not find/load PZGMainMenuScene layer");
        }

        director->replaceScene(scene);
        AXLOGI("AppDelegate::scheduledLoading -> PZGMainMenuScene");
        return;
    }

    // Fallback to keep the app alive if menu creation fails.
    auto* loading = PZGLoadingScene::scene();
    if (loading) {
        director->replaceScene(loading);
        AXLOGE("AppDelegate::scheduledLoading fallback -> PZGLoadingScene");
    }
}

void AppDelegate::applicationDidEnterBackground() {
    AXLOGI("AppDelegate::applicationDidEnterBackground");
    Director::getInstance()->stopAnimation();
    AudioEngine::pauseAll();
}

void AppDelegate::applicationWillEnterForeground() {
    AXLOGI("AppDelegate::applicationWillEnterForeground");
    Director::getInstance()->startAnimation();
    AudioEngine::resumeAll();
}

void AppDelegate::applicationWillQuit() {
    AXLOGI("AppDelegate::applicationWillQuit");
}
