#include "PZLegacyCompat.h"
#include "AppDelegate.h"
#include "PZGGameFieldScene.h"
#include "PZGLoadingScene.h"
#include "SharedData/PZGSharedData.h"
#include "PZCrashReporter.h"

USING_NS_AX;

AppDelegate::AppDelegate() = default;
AppDelegate::~AppDelegate() = default;

void AppDelegate::initGfxContextAttrs() {
    // red, green, blue, alpha, depth, stencil, multisamplesCount
    GfxContextAttrs gfxContextAttrs = {8, 8, 8, 8, 24, 8, 0};
    RenderView::setGfxContextAttrs(gfxContextAttrs);
}

void AppDelegate::setDebugModeEnabled(bool enable) {
    auto* gf = PZGGameFieldScene::shared();
    if (gf) gf->setDebugModeEnabled(enable);
}

bool AppDelegate::applicationDidFinishLaunching() {
    AXLOGI("AppDelegate::applicationDidFinishLaunching begin");
    PZCrashReporter::install();
    AXLOGI("Crash report path: {}", PZCrashReporter::getCrashReportPath());
    auto* director = Director::getInstance();
    auto* renderView = director->getRenderView();
    if (!renderView) {
        renderView = RenderViewImpl::create("Bike Race Escape");
        director->setRenderView(renderView);
    }

    director->setAnimationInterval(1.0f / 60.0f);
    renderView->setDesignResolutionSize(960, 640, ResolutionPolicy::EXACT_FIT);

    auto* fileUtils = FileUtils::getInstance();
    fileUtils->setSearchPaths({
        "runtime/axslc",  // compiled shaders (generated by Axmol build)
        "runtime",
        "Content/Images/HD",
        "Content/Images/SD",
        "Content/Sounds",
        "Content",
        "",
    });

    // Keep the old loading flow as the initial runtime entry.
    auto* scene = PZGLoadingScene::scene();
    if (!scene) {
        AXLOGE("PZGLoadingScene::scene() returned null");
        return false;
    }
    director->runWithScene(scene);
    AXLOGI("AppDelegate::applicationDidFinishLaunching end");
    return true;
}

void AppDelegate::scheduledLoading() {
    auto* director = Director::getInstance();
    auto* scene = PZGLoadingScene::scene();
    if (scene) director->replaceScene(scene);
}

void AppDelegate::applicationDidEnterBackground() {
    AXLOGI("AppDelegate::applicationDidEnterBackground");
    Director::getInstance()->stopAnimation();
    AudioEngine::pauseAll();
}

void AppDelegate::applicationWillEnterForeground() {
    AXLOGI("AppDelegate::applicationWillEnterForeground");
    Director::getInstance()->startAnimation();
    AudioEngine::resumeAll();
}

void AppDelegate::applicationWillQuit() {
    AXLOGI("AppDelegate::applicationWillQuit");
}
