#include "PZLegacyCompat.h"
#include "AppDelegate.h"
#include "PZGGameFieldScene.h"
#include "PZGCharacterMenu.h"
#include "PZGLoadingScene.h"
#include "PZGMainMenuScene.h"
#include "SharedData/PZGSharedData.h"
#include "PZCrashReporter.h"
#include "Ads/AdsController.h"
#include "Ads/AdsConfig.h"
#include "Ads/Providers/AdsProviderAdMob.h"

USING_NS_AX;

AppDelegate::AppDelegate() = default;
AppDelegate::~AppDelegate() = default;

void AppDelegate::initGfxContextAttrs() {
    // red, green, blue, alpha, depth, stencil, multisamplesCount
    GfxContextAttrs gfxContextAttrs = {8, 8, 8, 8, 24, 8, 0};
    RenderView::setGfxContextAttrs(gfxContextAttrs);
}

void AppDelegate::setDebugModeEnabled(bool enable) {
    auto* gf = PZGGameFieldScene::shared();
    if (gf) gf->setDebugModeEnabled(enable);
}

bool AppDelegate::applicationDidFinishLaunching() {
    AXLOGI("AppDelegate::applicationDidFinishLaunching begin");
    PZCrashReporter::install();
    AXLOGI("Crash report path: {}", PZCrashReporter::getCrashReportPath());
    auto* director = Director::getInstance();
    auto* renderView = director->getRenderView();
    if (!renderView) {
        renderView = RenderViewImpl::create("Bike Race Escape");
        director->setRenderView(renderView);
    }

    director->setAnimationInterval(1.0f / 60.0f);
    // Responsive resolution policy:
    // - `EXACT_FIT` stretches (non-uniform) -> bad for pixel art/UI
    // - `SHOW_ALL` letterboxes
    // - `NO_BORDER` crops
    // - `FIXED_HEIGHT` keeps vertical size stable and expands/shrinks horizontal view based on device AR.
    //   This avoids stretch while also avoiding letterbox/crop in most landscape iOS cases.
    renderView->setDesignResolutionSize(960, 640, ResolutionPolicy::FIXED_HEIGHT);

    auto* fileUtils = FileUtils::getInstance();
    std::vector<std::string> searchPaths = {
        "runtime/axslc",  // compiled shaders (generated by Axmol build)
        "runtime",
        // On Apple we package Content/* into the app bundle root (Images/..., Sounds/...) via ax_mark_multi_resources(RES_TO "Resources").
        // Keep both layouts in search paths to avoid platform-specific resource bugs.
        "Images/HD",
        "Images/SD",
        "Sounds",
        "Fonts",
        "Content/Images/HD",
        "Content/Images/SD",
        "Content/Sounds",
        "Content/Fonts",
        "Content",
        "",
    };
    fileUtils->setSearchPaths(searchPaths);

    // Log search paths for debugging resource loading issues
    auto allSearchPaths = fileUtils->getSearchPaths();
    AXLOGI("Resource search paths:");
    for (const auto& path : allSearchPaths) {
        AXLOGI("  - {}", path);
    }

    // Log font path for debugging - fonts are loaded on-demand by Label::createWithBMFont
    auto fontFullPath = fileUtils->fullPathForFilename("MainFont.fnt");
    if (!fontFullPath.empty()) {
        AXLOGI("MainFont.fnt found at: {}", fontFullPath);
    } else {
        AXLOGW("MainFont.fnt not found in search paths - labels may not render");
    }

    // Keep the old loading flow as the initial runtime entry.
    auto* scene = PZGLoadingScene::scene();
    if (!scene) {
        AXLOGE("PZGLoadingScene::scene() returned null");
        return false;
    }
    director->runWithScene(scene);
    AXLOGI("AppDelegate::applicationDidFinishLaunching end");
    return true;
}

void AppDelegate::scheduledLoading() {
    AXLOGI("AppDelegate::scheduledLoading begin");
    auto* director = Director::getInstance();
    // Legacy port: the old loading scene re-entered itself; that just creates a loop + black screen if any resource is missing.
    // Do the minimum bootstrap then go to the first real UI.
    auto* sd = PZGSharedData::sharedInstanse();
    if (sd) sd->readDataFromFile();

    // ---- Ads bootstrap (Content/ads.plist) ----
    {
        auto* ads = PZ::AdsController::shared();
        ads->loadConfigFromPlist();

        // Respect "Remove Ads" purchase flag.
        if (auto* sc = PZSettingsController::shared()) {
            ads->setAdsEnabled(!sc->removeAds);
        }

        // For now we support AdMob provider selection only (provider itself is still a stub unless SDKs are added).
        const auto& cfg = ads->config();
        if (cfg.admobEnabled) {
            ads->setProvider(std::make_unique<PZ::AdsProviderAdMob>());
#if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
            ads->initialize(cfg.admob.appIdIOS);
#elif (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
            ads->initialize(cfg.admob.appIdAndroid);
#else
            ads->initialize("");
#endif
        }
    }

    // Start at legacy main menu (it knows how to bootstrap its own UI via load()).
    if (auto* scene = PZGMainMenuScene::scene()) {
        AXLOGI("PZGMainMenuScene created, children count: {}", scene->getChildren().size());

        // Try to find and load the main menu layer
        bool menuLoaded = false;
        if (!scene->getChildren().empty()) {
            for (auto child : scene->getChildren()) {
                if (auto* layer = dynamic_cast<PZGMainMenuScene*>(child)) {
                    AXLOGI("Found PZGMainMenuScene layer, calling load()");
                    layer->load("InterfaceMM");
                    menuLoaded = true;
                    break;
                }
            }
        }

        if (!menuLoaded) {
            AXLOGW("Warning: Could not find/load PZGMainMenuScene layer");
        }

        director->replaceScene(scene);
        AXLOGI("AppDelegate::scheduledLoading -> PZGMainMenuScene");
        return;
    }

    // Fallback to keep the app alive if menu creation fails.
    auto* loading = PZGLoadingScene::scene();
    if (loading) {
        director->replaceScene(loading);
        AXLOGE("AppDelegate::scheduledLoading fallback -> PZGLoadingScene");
    }
}

void AppDelegate::applicationDidEnterBackground() {
    AXLOGI("AppDelegate::applicationDidEnterBackground");
    Director::getInstance()->stopAnimation();
    AudioEngine::pauseAll();
}

void AppDelegate::applicationWillEnterForeground() {
    AXLOGI("AppDelegate::applicationWillEnterForeground");
    Director::getInstance()->startAnimation();
    AudioEngine::resumeAll();
}

void AppDelegate::applicationWillQuit() {
    AXLOGI("AppDelegate::applicationWillQuit");
}
